# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='academic_degree',
            field=models.CharField(default='\u672c\u79d1', max_length=20, verbose_name='\u5b66\u4f4d'),
        ),
    ]
