# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-08 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170906_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('train_org', '\u57f9\u8bad\u673a\u6784'), ('individual', '\u4e2a\u4eba'), ('university', '\u9ad8\u6821')], default='train_org', max_length=20, verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
    ]
