# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_teacher_academic_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='in_a_word',
            field=models.CharField(default='', max_length=20, verbose_name='\u4e00\u53e5\u8bdd\u4ecb\u7ecd'),
        ),
    ]
