# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_courseorg_in_a_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='in_a_word',
            field=models.CharField(default='', max_length=20, verbose_name='\u4e00\u53e5\u8bdd\u5c55\u793a'),
        ),
    ]
