# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170912_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(default='', max_length=20, verbose_name='\u6587\u4ef6\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='\u8001\u5e08\u544a\u8bc9\u4f60\u80fd\u5b66\u5230\u4ec0\u4e48'),
        ),
    ]
