# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170914_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='new_email',
            field=models.EmailField(default='', max_length=50, verbose_name='\u65b0\u90ae\u7bb1'),
        ),
    ]
